import React from "react";
import { DEMO_POSTS } from "@/data/posts";
import { PostDataType } from "@/data/types";
import Badge from "@/shared/Badge";
import Image from "next/image";
import travelhero2Image from "@/images/company/cancellationpolicy.png";
import Link from "next/link";
import { Route } from "@/routers/types";

const Page = ({
    params,
    searchParams,
}: {
    params: { stepIndex: string };
    searchParams?: { [key: string]: string | string[] | undefined };
}) => {
    const renderHeader = () => {
        return (
            <header className="container rounded-xl">
                <div className="max-w-screen-md mx-auto space-y-5">
                    <h1
                        className=" text-neutral-900 font-semibold text-5xl md:text-5xl md:!leading-[120%] lg:text-5xl dark:text-neutral-100 max-w-4xl flex justify-center"
                        title="Quiet ingenuity: 120,000 lunches and counting"
                    >
                        Terms & Conditions
                    </h1>
                    <div className="w-full border-b border-neutral-100 dark:border-neutral-800"></div>
                </div>
            </header>
        );
    };

    const renderContent = () => {
        return (
            <div
                id="single-entry-content"
                className="prose dark:prose-invert prose-sm !max-w-screen-md sm:prose lg:prose-lg mx-auto dark:prose-dark"
            >
                <ol>
                    <li>General Terms:</li>
                    <ul>
                        <li>
                            {`By accessing and placing an order with TickYourList (registered under Scrollit), confirm that you are in agreement with and bound by the terms of service contained in the Terms & Conditions outlined below. These terms apply to the entire website and any email or other type of communication between you and TickYourList.`}
                        </li>
                        <li>
                            {`Under no circumstances shall TickYourList team be liable for any direct, indirect, special, incidental or consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on this site, even if TickYourList team or an authorized representative has been advised of the possibility of such damages. If your use of materials from this site results in the need for servicing, repair or correction of equipment or data, you assume any costs thereof.`}
                        </li>
                        <li>{`TickYourList will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve the resource rights to change prices and revise the usage policy at any moment.`}</li>
                    </ul>
                    <li>
                        License:
                        <ul>
                            <li>
                                {`TickYourList grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the website strictly in accordance with the terms of this Agreement.`}
                            </li>
                            <li>
                                {`These Terms & Conditions are a contract between you and TickYourList (referred to in these Terms & Conditions as “TickYourList”, “us”, “we” or “our”), the provider of the TickYourList website and the services accessible from the TickYourList website (which are collectively referred to in these Terms & Conditions as the “TickYourList Service”).`}
                            </li>
                            <li>{`You are agreeing to be bound by these Terms & Conditions. If you do not agree to these Terms & Conditions, please do not use the TickYourList Service. In these Terms & Conditions, “you” refers both to you as an individual and to the entity you represent. If you violate any of these Terms & Conditions, we reserve the right to cancel your account or block access to your account without notice.`}</li>

                        </ul>
                    </li>
                    <li>
                        Definitions and key terms:
                        <ul>
                            <li>
                                {`To help explain things as clearly as possible in this Terms & Conditions, every time any of these terms are referenced, are strictly defined as:`}
                            </li>
                            <li>
                                {`Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.`}
                            </li>
                            <li>{`Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to TickYourList, 119, Backside Basement, Sarvanchal Residency, New Delhi, India that is responsible for your information under this Terms & Conditions.`}</li>
                            <li>{`Country: where TickYourList or the owners/founders of TickYourList are based, in this case is United Arab Emirates`}</li>
                            <li>{`Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit TickYourList and use the services.`}</li>
                            <li>{`Service: refers to the service provided by TickYourList as described in the relative terms (if available) and on this platform.`}</li>
                            <li>{`Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.`}</li>
                            <li>{`Website: TickYourList's site, which can be accessed via this URL:`} {<Link href="https://www.tickyourlist.com/" target="_blank">www.tickyourlist.com</Link>}</li>
                            <li>{`You: a person or entity that is registered with TickYourList to use the Services.`}</li>
                        </ul>
                    </li>
                    <li>
                        Restrictions:
                        <ul>
                            You agree not to, and you will not permit others to:
                            <li>
                                {`License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the website or make the platform available to any third party.`}
                            </li>
                            <li>
                                {`Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the website.`}
                            </li>
                            <li>{`Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of TickYourList or its affiliates, partners, suppliers or the licensors of the website.`}</li>
                        </ul>
                    </li>
                    <li>
                        Return and Refund Policy:
                        <ul>
                            <li>
                                {`Thanks for shopping at TickYourList. We appreciate the fact that you like to buy the stuff we build. We also want to make sure you have a rewarding experience while you're exploring, evaluating, and purchasing our products.`}
                            </li>
                            <li>
                                {`As with any shopping experience, there are terms and conditions that apply to transactions at TickYourList. We'll be as brief as our attorneys will allow. The main thing to remember is that by placing an order or making a purchase at TickYourList, you agree to the terms along with TickYourList's Privacy Policy.`}
                            </li>
                            <li>{`If, for any reason, you are not completely satisfied with any good or service that we provide, don't hesitate to contact us and we will discuss any of the issues you are going through with our product.`}</li>
                        </ul>
                    </li>
                    <li>
                        Cancellation Policy:
                        <ul>
                            <li>
                                {`Please note that tickets purchased through our platform are non-refundable. We appreciate your understanding in this matter.`}
                            </li>
                        </ul>
                    </li>
                    <li>
                        Your Suggestions:
                        <ul>
                            <li>
                                {`Any feedback, comments, ideas, improvements or suggestions (collectively, "Suggestions") shall be provided by you to TickYourList with respect to the website remain the sole and exclusive property of TickYourList.`}
                            </li>
                            <li>
                                {`TickYourList shall be free to use, copy, modify, publish, or redistribute the Suggestions for any purpose and in any way without any credit or any compensation to you.`}
                            </li>
                        </ul>
                    </li>
                    <li>
                        Your Consent:
                        <ul>
                            <li>
                                {`We've updated our Terms & Conditions to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our website, registering an account, or making a purchase, you hereby consent to our Terms & Conditions.`}
                            </li>
                        </ul>
                    </li>
                    <li>
                        Links to Other Websites:
                        <ul>
                            <li>
                                {`These Terms & Conditions apply only to the Services. The Services may contain links to other websites not operated or controlled by TickYourList. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Terms & Conditions are no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website’s own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.`}
                            </li>
                        </ul>
                    </li>
                    <li>
                        Cookies:
                        <ul>
                            <li>
                                {`TickYourList uses "Cookies" to identify the areas of our website that you have visited. A cookie is a small piece of data stored on your computer or mobile device by your web browser. We use cookies to enhance the performance and functionality of our website but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the website as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of cookies. However, if you disable cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.`}
                            </li>
                        </ul>
                    </li>
                    <li>
                        Changes To Our Terms & Conditions:
                        <ul>
                            <li>
                                {`You acknowledge and agree that we may stop (permanently or temporarily) providing the Service (or any features within the Service) to you or to users generally at our sole discretion, without prior notice to you. You may stop using the Service at any time. You do not need to specifically inform us when you stop using the Service.`}
                            </li>
                            <li>
                                {`We may revise these Terms & Conditions from time to time. The changes will not be retroactive, and the most current version of the Terms & Conditions, which will always be at TickYourList website, will govern our relationship with you. We will try to notify you of material revisions, for example via a service notification or an email to the email associated with your account. By continuing to access or use the Services after those revisions become effective, you agree to be bound by the revised Terms & Conditions.`}
                            </li>
                        </ul>
                    </li>
                    <li>
                        Contact Us:
                        <ul>
                            <li>
                                {`If you have any questions about these Terms & Conditions, please contact us at: `}{<span className="font-bold">help@tickyourlist.com</span>}
                            </li>
                        </ul>
                    </li>
                </ol>
            </div>
        );
    };

    const renderPostRelated = (post: PostDataType) => {
        return (
            <div
                key={post.id}
                className="relative aspect-w-3 aspect-h-4 rounded-3xl overflow-hidden group"
            >
                <Link href={post.href as Route} />
                <Image
                    className="object-cover transform group-hover:scale-105 transition-transform duration-300"
                    src={post.featuredImage}
                    fill
                    sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
                    alt=""
                />
                <div>
                    <div className="absolute bottom-0 inset-x-0 h-1/2 bg-gradient-to-t from-black"></div>
                </div>
                <div className="flex flex-col justify-end items-start text-xs text-neutral-300 space-y-2.5 p-4">
                    <Badge name="Categories" />
                    <h2 className="block text-lg font-semibold text-white ">
                        <span className="line-clamp-2">{post.title}</span>
                    </h2>

                    <div className="flex">
                        <span className="block text-neutral-200 hover:text-white font-medium truncate">
                            {post.author.displayName}
                        </span>
                        <span className="mx-1.5 font-medium">·</span>
                        <span className="font-normal truncate">{post.date}</span>
                    </div>
                </div>
                <Link href={post.href as Route} />
            </div>
        );
    };

    return (
        <div className="nc-PageSingle pt-8 lg:pt-16 ">
            {renderHeader()}
            <div className="container my-10 sm:my-12 ">
                <Image className="w-full rounded-xl" src={travelhero2Image} alt="" />
            </div>

            <div className="nc-SingleContent container space-y-10">
                {renderContent()}
                {/* {renderTags()}
                <div className="max-w-screen-md mx-auto border-b border-t border-neutral-100 dark:border-neutral-700"></div>
                {renderAuthor()}
                {renderCommentForm()} */}
                {/* {renderCommentLists()} */}
            </div>
            <div className="relative bg-neutral-100 dark:bg-neutral-800 py-16 lg:py-28 mt-16 lg:mt-24">
                <div className="container ">
                    <h2 className="text-3xl font-semibold">New blogs</h2>
                    <div className="mt-10 grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6 md:gap-8">
                        {/*  */}
                        {DEMO_POSTS.filter((_, i) => i < 4).map(renderPostRelated)}
                        {/*  */}
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Page;
