export const countries = [
    { name: 'Afghanistan', nativeName: 'افغانستان', code: '+93', flag: '🇦🇫' },
    { name: 'Albania', nativeName: 'Shqipëri', code: '+355', flag: '🇦🇱' },
    { name: 'Algeria', nativeName: 'الجزائر', code: '+213', flag: '🇩🇿' },
    { name: 'Andorra', nativeName: 'Andorra', code: '+376', flag: '🇦🇩' },
    { name: 'Angola', nativeName: 'Angola', code: '+244', flag: '🇦🇴' },
    { name: 'Antigua and Barbuda', nativeName: 'Antigua and Barbuda', code: '+1268', flag: '🇦🇬' },
    { name: 'Argentina', nativeName: 'Argentina', code: '+54', flag: '🇦🇷' },
    { name: 'Armenia', nativeName: 'Հայաստան', code: '+374', flag: '🇦🇲' },
    { name: 'Australia', nativeName: 'Australia', code: '+61', flag: '🇦🇺' },
    { name: 'Austria', nativeName: 'Österreich', code: '+43', flag: '🇦🇹' },
    { name: 'Azerbaijan', nativeName: 'Azərbaycan', code: '+994', flag: '🇦🇿' },
    { name: 'Bahamas', nativeName: 'Bahamas', code: '+1242', flag: '🇧🇸' },
    { name: 'Bahrain', nativeName: 'البحرين', code: '+973', flag: '🇧🇭' },
    { name: 'Bangladesh', nativeName: 'বাংলাদেশ', code: '+880', flag: '🇧🇩' },
    { name: 'Barbados', nativeName: 'Barbados', code: '+1246', flag: '🇧🇧' },
    { name: 'Belarus', nativeName: 'Белару́сь', code: '+375', flag: '🇧🇾' },
    { name: 'Belgium', nativeName: 'België', code: '+32', flag: '🇧🇪' },
    { name: 'Belize', nativeName: 'Belize', code: '+501', flag: '🇧🇿' },
    { name: 'Benin', nativeName: 'Bénin', code: '+229', flag: '🇧🇯' },
    { name: 'Bhutan', nativeName: 'འབྲུག་ཡུལ', code: '+975', flag: '🇧🇹' },
    { name: 'Bolivia', nativeName: 'Bolivia', code: '+591', flag: '🇧🇴' },
    { name: 'Bosnia and Herzegovina', nativeName: 'Bosna i Hercegovina', code: '+387', flag: '🇧🇦' },
    { name: 'Botswana', nativeName: 'Botswana', code: '+267', flag: '🇧🇼' },
    { name: 'Brazil', nativeName: 'Brasil', code: '+55', flag: '🇧🇷' },
    { name: 'Brunei', nativeName: 'Brunei', code: '+673', flag: '🇧🇳' },
    { name: 'Bulgaria', nativeName: 'България', code: '+359', flag: '🇧🇬' },
    { name: 'Burkina Faso', nativeName: 'Burkina Faso', code: '+226', flag: '🇧🇫' },
    { name: 'Burundi', nativeName: 'Burundi', code: '+257', flag: '🇧🇮' },
    { name: 'Cambodia', nativeName: 'Kâmpŭchéa', code: '+855', flag: '🇰🇭' },
    { name: 'Cameroon', nativeName: 'Cameroon', code: '+237', flag: '🇨🇲' },
    { name: 'Canada', nativeName: 'Canada', code: '+1', flag: '🇨🇦' },
    { name: 'Cape Verde', nativeName: 'Cabo Verde', code: '+238', flag: '🇨🇻' },
    { name: 'Central African Republic', nativeName: 'République centrafricaine', code: '+236', flag: '🇨🇫' },
    { name: 'Chad', nativeName: 'Tchad', code: '+235', flag: '🇹🇩' },
    { name: 'Chile', nativeName: 'Chile', code: '+56', flag: '🇨🇱' },
    { name: 'China', nativeName: '中国', code: '+86', flag: '🇨🇳' },
    { name: 'Colombia', nativeName: 'Colombia', code: '+57', flag: '🇨🇴' },
    { name: 'Comoros', nativeName: 'Komori', code: '+269', flag: '🇰🇲' },
    { name: 'Congo', nativeName: 'République du Congo', code: '+242', flag: '🇨🇬' },
    { name: 'Costa Rica', nativeName: 'Costa Rica', code: '+506', flag: '🇨🇷' },
    { name: 'Croatia', nativeName: 'Hrvatska', code: '+385', flag: '🇭🇷' },
    { name: 'Cuba', nativeName: 'Cuba', code: '+53', flag: '🇨🇺' },
    { name: 'Cyprus', nativeName: 'Κύπρος', code: '+357', flag: '🇨🇾' },
    { name: 'Czech Republic', nativeName: 'Česká republika', code: '+420', flag: '🇨🇿' },
    { name: 'Denmark', nativeName: 'Danmark', code: '+45', flag: '🇩🇰' },
    { name: 'Djibouti', nativeName: 'Djibouti', code: '+253', flag: '🇩🇯' },
    { name: 'Dominica', nativeName: 'Dominica', code: '+1767', flag: '🇩🇲' },
    { name: 'Dominican Republic', nativeName: 'República Dominicana', code: '+1849', flag: '🇩🇴' },
    { name: 'Ecuador', nativeName: 'Ecuador', code: '+593', flag: '🇪🇨' },
    { name: 'Egypt', nativeName: 'مصر', code: '+20', flag: '🇪🇬' },
    { name: 'El Salvador', nativeName: 'El Salvador', code: '+503', flag: '🇸🇻' },
    { name: 'Equatorial Guinea', nativeName: 'Guinea Ecuatorial', code: '+240', flag: '🇬🇶' },
    { name: 'Eritrea', nativeName: 'ኤርትራ', code: '+291', flag: '🇪🇷' },
    { name: 'Estonia', nativeName: 'Eesti', code: '+372', flag: '🇪🇪' },
    { name: 'Ethiopia', nativeName: 'ኢትዮጵያ', code: '+251', flag: '🇪🇹' },
    { name: 'Fiji', nativeName: 'Fiji', code: '+679', flag: '🇫🇯' },
    { name: 'Finland', nativeName: 'Suomi', code: '+358', flag: '🇫🇮' },
    { name: 'France', nativeName: 'France', code: '+33', flag: '🇫🇷' },
    { name: 'Gabon', nativeName: 'Gabon', code: '+241', flag: '🇬🇦' },
    { name: 'Gambia', nativeName: 'Gambia', code: '+220', flag: '🇬🇲' },
    { name: 'Georgia', nativeName: 'საქართველო', code: '+995', flag: '🇬🇪' },
    { name: 'Germany', nativeName: 'Deutschland', code: '+49', flag: '🇩🇪' },
    { name: 'Ghana', nativeName: 'Ghana', code: '+233', flag: '🇬🇭' },
    { name: 'Greece', nativeName: 'Ελλάδα', code: '+30', flag: '🇬🇷' },
    { name: 'Grenada', nativeName: 'Grenada', code: '+1473', flag: '🇬🇩' },
    { name: 'Guatemala', nativeName: 'Guatemala', code: '+502', flag: '🇬🇹' },
    { name: 'Guinea', nativeName: 'Guinée', code: '+224', flag: '🇬🇳' },
    { name: 'Guinea-Bissau', nativeName: 'Guiné-Bissau', code: '+245', flag: '🇬🇼' },
    { name: 'Guyana', nativeName: 'Guyana', code: '+592', flag: '🇬🇾' },
    { name: 'Haiti', nativeName: 'Haïti', code: '+509', flag: '🇭🇹' },
    { name: 'Honduras', nativeName: 'Honduras', code: '+504', flag: '🇭🇳' },
    { name: 'Hungary', nativeName: 'Magyarország', code: '+36', flag: '🇭🇺' },
    { name: 'Iceland', nativeName: 'Ísland', code: '+354', flag: '🇮🇸' },
    { name: 'India', nativeName: 'भारत', code: '+91', flag: '🇮🇳' },
    { name: 'Indonesia', nativeName: 'Indonesia', code: '+62', flag: '🇮🇩' },
    { name: 'Iran', nativeName: 'ایران', code: '+98', flag: '🇮🇷' },
    { name: 'Iraq', nativeName: 'العراق', code: '+964', flag: '🇮🇶' },
    { name: 'Ireland', nativeName: 'Éire', code: '+353', flag: '🇮🇪' },
    { name: 'Israel', nativeName: 'יִשְׂרָאֵל', code: '+972', flag: '🇮🇱' },
    { name: 'Italy', nativeName: 'Italia', code: '+39', flag: '🇮🇹' },
    { name: 'Jamaica', nativeName: 'Jamaica', code: '+1876', flag: '🇯🇲' },
    { name: 'Japan', nativeName: '日本', code: '+81', flag: '🇯🇵' },
    { name: 'Jordan', nativeName: 'الأردن', code: '+962', flag: '🇯🇴' },
    { name: 'Kazakhstan', nativeName: 'Қазақстан', code: '+7', flag: '🇰🇿' },
    { name: 'Kenya', nativeName: 'Kenya', code: '+254', flag: '🇰🇪' },
    { name: 'Kiribati', nativeName: 'Kiribati', code: '+686', flag: '🇰🇮' },
    { name: 'Kuwait', nativeName: 'الكويت', code: '+965', flag: '🇰🇼' },
    { name: 'Kyrgyzstan', nativeName: 'Кыргызстан', code: '+996', flag: '🇰🇬' },
    { name: 'Laos', nativeName: 'ລາວ', code: '+856', flag: '🇱🇦' },
    { name: 'Latvia', nativeName: 'Latvija', code: '+371', flag: '🇱🇻' },
    { name: 'Lebanon', nativeName: 'لبنان', code: '+961', flag: '🇱🇧' },
    { name: 'Lesotho', nativeName: 'Lesotho', code: '+266', flag: '🇱🇸' },
    { name: 'Liberia', nativeName: 'Liberia', code: '+231', flag: '🇱🇷' },
    { name: 'Libya', nativeName: 'ليبيا', code: '+218', flag: '🇱🇾' },
    { name: 'Liechtenstein', nativeName: 'Liechtenstein', code: '+423', flag: '🇱🇮' },
    { name: 'Lithuania', nativeName: 'Lietuva', code: '+370', flag: '🇱🇹' },
    { name: 'Luxembourg', nativeName: 'Luxembourg', code: '+352', flag: '🇱🇺' },
    { name: 'Madagascar', nativeName: 'Madagasikara', code: '+261', flag: '🇲🇬' },
    { name: 'Malawi', nativeName: 'Malawi', code: '+265', flag: '🇲🇼' },
    { name: 'Malaysia', nativeName: 'Malaysia', code: '+60', flag: '🇲🇾' },
    { name: 'Maldives', nativeName: 'Dhivehi Raajje', code: '+960', flag: '🇲🇻' },
    { name: 'Mali', nativeName: 'Mali', code: '+223', flag: '🇲🇱' },
    { name: 'Malta', nativeName: 'Malta', code: '+356', flag: '🇲🇹' },
    { name: 'Marshall Islands', nativeName: 'M̧ajeļ', code: '+692', flag: '🇲🇭' },
    { name: 'Mauritania', nativeName: 'موريتانيا', code: '+222', flag: '🇲🇷' },
    { name: 'Mauritius', nativeName: 'Maurice', code: '+230', flag: '🇲🇺' },
    { name: 'Mexico', nativeName: 'México', code: '+52', flag: '🇲🇽' },
    { name: 'Micronesia', nativeName: 'Micronesia', code: '+691', flag: '🇫🇲' },
    { name: 'Moldova', nativeName: 'Moldova', code: '+373', flag: '🇲🇩' },
    { name: 'Monaco', nativeName: 'Monaco', code: '+377', flag: '🇲🇨' },
    { name: 'Mongolia', nativeName: 'Монгол улс', code: '+976', flag: '🇲🇳' },
    { name: 'Montenegro', nativeName: 'Crna Gora', code: '+382', flag: '🇲🇪' },
    { name: 'Morocco', nativeName: 'المغرب', code: '+212', flag: '🇲🇦' },
    { name: 'Mozambique', nativeName: 'Moçambique', code: '+258', flag: '🇲🇿' },
    { name: 'Myanmar', nativeName: 'မြန်မာ', code: '+95', flag: '🇲🇲' },
    { name: 'Namibia', nativeName: 'Namibia', code: '+264', flag: '🇳🇦' },
    { name: 'Nauru', nativeName: 'Nauru', code: '+674', flag: '🇳🇷' },
    { name: 'Nepal', nativeName: 'नेपाल', code: '+977', flag: '🇳🇵' },
    { name: 'Netherlands', nativeName: 'Nederland', code: '+31', flag: '🇳🇱' },
    { name: 'New Zealand', nativeName: 'New Zealand', code: '+64', flag: '🇳🇿' },
    { name: 'Nicaragua', nativeName: 'Nicaragua', code: '+505', flag: '🇳🇮' },
    { name: 'Niger', nativeName: 'Niger', code: '+227', flag: '🇳🇪' },
    { name: 'Nigeria', nativeName: 'Nigeria', code: '+234', flag: '🇳🇬' },
    { name: 'North Korea', nativeName: '조선민주주의인민공화국', code: '+850', flag: '🇰🇵' },
    { name: 'North Macedonia', nativeName: 'Северна Македонија', code: '+389', flag: '🇲🇰' },
    { name: 'Norway', nativeName: 'Norge', code: '+47', flag: '🇳🇴' },
    { name: 'Oman', nativeName: 'عمان', code: '+968', flag: '🇴🇲' },
    { name: 'Pakistan', nativeName: 'پاکستان', code: '+92', flag: '🇵🇰' },
    { name: 'Palau', nativeName: 'Palau', code: '+680', flag: '🇵🇼' },
    { name: 'Palestine', nativeName: 'فلسطين', code: '+970', flag: '🇵🇸' },
    { name: 'Panama', nativeName: 'Panamá', code: '+507', flag: '🇵🇦' },
    { name: 'Papua New Guinea', nativeName: 'Papua Niugini', code: '+675', flag: '🇵🇬' },
    { name: 'Paraguay', nativeName: 'Paraguay', code: '+595', flag: '🇵🇾' },
    { name: 'Peru', nativeName: 'Perú', code: '+51', flag: '🇵🇪' },
    { name: 'Philippines', nativeName: 'Pilipinas', code: '+63', flag: '🇵🇭' },
    { name: 'Poland', nativeName: 'Polska', code: '+48', flag: '🇵🇱' },
    { name: 'Portugal', nativeName: 'Portugal', code: '+351', flag: '🇵🇹' },
    { name: 'Qatar', nativeName: 'قطر', code: '+974', flag: '🇶🇦' },
    { name: 'Romania', nativeName: 'România', code: '+40', flag: '🇷🇴' },
    { name: 'Russia', nativeName: 'Россия', code: '+7', flag: '🇷🇺' },
    { name: 'Rwanda', nativeName: 'Rwanda', code: '+250', flag: '🇷🇼' },
    { name: 'Saint Kitts and Nevis', nativeName: 'Saint Kitts and Nevis', code: '+1869', flag: '🇰🇳' },
    { name: 'Saint Lucia', nativeName: 'Saint Lucia', code: '+1758', flag: '🇱🇨' },
    { name: 'Saint Vincent and the Grenadines', nativeName: 'Saint Vincent and the Grenadines', code: '+1784', flag: '🇻🇨' },
    { name: 'Samoa', nativeName: 'Samoa', code: '+685', flag: '🇼🇸' },
    { name: 'San Marino', nativeName: 'San Marino', code: '+378', flag: '🇸🇲' },
    { name: 'Sao Tome and Principe', nativeName: 'São Tomé e Príncipe', code: '+239', flag: '🇸🇹' },
    { name: 'Saudi Arabia', nativeName: 'المملكة العربية السعودية', code: '+966', flag: '🇸🇦' },
    { name: 'Senegal', nativeName: 'Sénégal', code: '+221', flag: '🇸🇳' },
    { name: 'Serbia', nativeName: 'Србија', code: '+381', flag: '🇷🇸' },
    { name: 'Seychelles', nativeName: 'Seychelles', code: '+248', flag: '🇸🇨' },
    { name: 'Sierra Leone', nativeName: 'Sierra Leone', code: '+232', flag: '🇸🇱' },
    { name: 'Singapore', nativeName: 'Singapore', code: '+65', flag: '🇸🇬' },
    { name: 'Slovakia', nativeName: 'Slovensko', code: '+421', flag: '🇸🇰' },
    { name: 'Slovenia', nativeName: 'Slovenija', code: '+386', flag: '🇸🇮' },
    { name: 'Solomon Islands', nativeName: 'Solomon Islands', code: '+677', flag: '🇸🇧' },
    { name: 'Somalia', nativeName: 'Soomaaliya', code: '+252', flag: '🇸🇴' },
    { name: 'South Africa', nativeName: 'South Africa', code: '+27', flag: '🇿🇦' },
    { name: 'South Korea', nativeName: '대한민국', code: '+82', flag: '🇰🇷' },
    { name: 'South Sudan', nativeName: 'South Sudan', code: '+211', flag: '🇸🇸' },
    { name: 'Spain', nativeName: 'España', code: '+34', flag: '🇪🇸' },
    { name: 'Sri Lanka', nativeName: 'śrī laṃkāva', code: '+94', flag: '🇱🇰' },
    { name: 'Sudan', nativeName: 'السودان', code: '+249', flag: '🇸🇩' },
    { name: 'Suriname', nativeName: 'Suriname', code: '+597', flag: '🇸🇷' },
    { name: 'Sweden', nativeName: 'Sverige', code: '+46', flag: '🇸🇪' },
    { name: 'Switzerland', nativeName: 'Schweiz', code: '+41', flag: '🇨🇭' },
    { name: 'Syria', nativeName: 'سوريا', code: '+963', flag: '🇸🇾' },
    { name: 'Tajikistan', nativeName: 'Тоҷикистон', code: '+992', flag: '🇹🇯' },
    { name: 'Tanzania', nativeName: 'Tanzania', code: '+255', flag: '🇹🇿' },
    { name: 'Thailand', nativeName: 'ประเทศไทย', code: '+66', flag: '🇹🇭' },
    { name: 'Timor-Leste', nativeName: 'Timor-Leste', code: '+670', flag: '🇹🇱' },
    { name: 'Togo', nativeName: 'Togo', code: '+228', flag: '🇹🇬' },
    { name: 'Tonga', nativeName: 'Tonga', code: '+676', flag: '🇹🇴' },
    { name: 'Trinidad and Tobago', nativeName: 'Trinidad and Tobago', code: '+1868', flag: '🇹🇹' },
    { name: 'Tunisia', nativeName: 'تونس', code: '+216', flag: '🇹🇳' },
    { name: 'Turkey', nativeName: 'Türkiye', code: '+90', flag: '🇹🇷' },
    { name: 'Turkmenistan', nativeName: 'Türkmenistan', code: '+993', flag: '🇹🇲' },
    { name: 'Tuvalu', nativeName: 'Tuvalu', code: '+688', flag: '🇹🇻' },
    { name: 'Uganda', nativeName: 'Uganda', code: '+256', flag: '🇺🇬' },
    { name: 'Ukraine', nativeName: 'Україна', code: '+380', flag: '🇺🇦' },
    { name: 'United Arab Emirates', nativeName: 'الإمارات العربية المتحدة', code: '+971', flag: '🇦🇪' },
    { name: 'United Kingdom', nativeName: 'United Kingdom', code: '+44', flag: '🇬🇧' },
    { name: 'United States', nativeName: 'United States', code: '+1', flag: '🇺🇸' },
    { name: 'Uruguay', nativeName: 'Uruguay', code: '+598', flag: '🇺🇾' },
    { name: 'Uzbekistan', nativeName: 'Uzbekiston', code: '+998', flag: '🇺🇿' },
    { name: 'Vanuatu', nativeName: 'Vanuatu', code: '+678', flag: '🇻🇺' },
    { name: 'Vatican City', nativeName: 'Città del Vaticano', code: '+39', flag: '🇻🇦' },
    { name: 'Venezuela', nativeName: 'Venezuela', code: '+58', flag: '🇻🇪' },
    { name: 'Vietnam', nativeName: 'Việt Nam', code: '+84', flag: '🇻🇳' },
    { name: 'Yemen', nativeName: 'اليَمَن', code: '+967', flag: '🇾🇪' },
    { name: 'Zambia', nativeName: 'Zambia', code: '+260', flag: '🇿🇲' },
    { name: 'Zimbabwe', nativeName: 'Zimbabwe', code: '+263', flag: '🇿🇼' }
  ];