export const countries = [
    { name: 'Afghanistan', nativeName: 'افغانستان', code: '+93', flag: '🇦🇫', countryCode: 'AF' },
    { name: 'Albania', nativeName: 'Shqipëri', code: '+355', flag: '🇦🇱', countryCode: 'AL' },
    { name: 'Algeria', nativeName: 'الجزائر', code: '+213', flag: '🇩🇿', countryCode: 'DZ' },
    { name: 'Andorra', nativeName: 'Andorra', code: '+376', flag: '🇦🇩', countryCode: 'AD' },
    { name: 'Angola', nativeName: 'Angola', code: '+244', flag: '🇦🇴', countryCode: 'AO' },
    { name: 'Antigua and Barbuda', nativeName: 'Antigua and Barbuda', code: '+1268', flag: '🇦🇬', countryCode: 'AG' },
    { name: 'Argentina', nativeName: 'Argentina', code: '+54', flag: '🇦🇷', countryCode: 'AR' },
    { name: 'Armenia', nativeName: 'Հայաստան', code: '+374', flag: '🇦🇲', countryCode: 'AM' },
    { name: 'Australia', nativeName: 'Australia', code: '+61', flag: '🇦🇺', countryCode: 'AU' },
    { name: 'Austria', nativeName: 'Österreich', code: '+43', flag: '🇦🇹', countryCode: 'AT' },
    { name: 'Azerbaijan', nativeName: 'Azərbaycan', code: '+994', flag: '🇦🇿', countryCode: 'AZ' },
    { name: 'Bahamas', nativeName: 'Bahamas', code: '+1242', flag: '🇧🇸', countryCode: 'BS' },
    { name: 'Bahrain', nativeName: 'البحرين', code: '+973', flag: '🇧🇭', countryCode: 'BH' },
    { name: 'Bangladesh', nativeName: 'বাংলাদেশ', code: '+880', flag: '🇧🇩', countryCode: 'BD' },
    { name: 'Barbados', nativeName: 'Barbados', code: '+1246', flag: '🇧🇧', countryCode: 'BB' },
    { name: 'Belarus', nativeName: 'Белару́сь', code: '+375', flag: '🇧🇾', countryCode: 'BY' },
    { name: 'Belgium', nativeName: 'België', code: '+32', flag: '🇧🇪', countryCode: 'BE' },
    { name: 'Belize', nativeName: 'Belize', code: '+501', flag: '🇧🇿', countryCode: 'BZ' },
    { name: 'Benin', nativeName: 'Bénin', code: '+229', flag: '🇧🇯', countryCode: 'BJ' },
    { name: 'Bhutan', nativeName: 'འབྲུག་ཡུལ', code: '+975', flag: '🇧🇹', countryCode: 'BT' },
    { name: 'Bolivia', nativeName: 'Bolivia', code: '+591', flag: '🇧🇴', countryCode: 'BO' },
    { name: 'Bosnia and Herzegovina', nativeName: 'Bosna i Hercegovina', code: '+387', flag: '🇧🇦', countryCode: 'BA' },
    { name: 'Botswana', nativeName: 'Botswana', code: '+267', flag: '🇧🇼', countryCode: 'BW' },
    { name: 'Brazil', nativeName: 'Brasil', code: '+55', flag: '🇧🇷', countryCode: 'BR' },
    { name: 'Brunei', nativeName: 'Brunei', code: '+673', flag: '🇧🇳', countryCode: 'BN' },
    { name: 'Bulgaria', nativeName: 'България', code: '+359', flag: '🇧🇬', countryCode: 'BG' },
    { name: 'Burkina Faso', nativeName: 'Burkina Faso', code: '+226', flag: '🇧🇫', countryCode: 'BF' },
    { name: 'Burundi', nativeName: 'Burundi', code: '+257', flag: '🇧🇮', countryCode: 'BI' },
    { name: 'Cambodia', nativeName: 'Kâmpŭchéa', code: '+855', flag: '🇰🇭', countryCode: 'KH' },
    { name: 'Cameroon', nativeName: 'Cameroon', code: '+237', flag: '🇨🇲', countryCode: 'CM' },
    { name: 'Canada', nativeName: 'Canada', code: '+1', flag: '🇨🇦', countryCode: 'CA' },
    { name: 'Cape Verde', nativeName: 'Cabo Verde', code: '+238', flag: '🇨🇻', countryCode: 'CV' },
    { name: 'Central African Republic', nativeName: 'République centrafricaine', code: '+236', flag: '🇨🇫', countryCode: 'CF' },
    { name: 'Chad', nativeName: 'Tchad', code: '+235', flag: '🇹🇩', countryCode: 'TD' },
    { name: 'Chile', nativeName: 'Chile', code: '+56', flag: '🇨🇱', countryCode: 'CL' },
    { name: 'China', nativeName: '中国', code: '+86', flag: '🇨🇳', countryCode: 'CN' },
    { name: 'Colombia', nativeName: 'Colombia', code: '+57', flag: '🇨🇴', countryCode: 'CO' },
    { name: 'Comoros', nativeName: 'Komori', code: '+269', flag: '🇰🇲', countryCode: 'KM' },
    { name: 'Congo', nativeName: 'République du Congo', code: '+242', flag: '🇨🇬', countryCode: 'CG' },
    { name: 'Costa Rica', nativeName: 'Costa Rica', code: '+506', flag: '🇨🇷', countryCode: 'CR' },
    { name: 'Croatia', nativeName: 'Hrvatska', code: '+385', flag: '🇭🇷', countryCode: 'HR' },
    { name: 'Cuba', nativeName: 'Cuba', code: '+53', flag: '🇨🇺', countryCode: 'CU' },
    { name: 'Cyprus', nativeName: 'Κύπρος', code: '+357', flag: '🇨🇾', countryCode: 'CY' },
    { name: 'Czech Republic', nativeName: 'Česká republika', code: '+420', flag: '🇨🇿', countryCode: 'CZ' },
    { name: 'Denmark', nativeName: 'Danmark', code: '+45', flag: '🇩🇰', countryCode: 'DK' },
    { name: 'Djibouti', nativeName: 'Djibouti', code: '+253', flag: '🇩🇯', countryCode: 'DJ' },
    { name: 'Dominica', nativeName: 'Dominica', code: '+1767', flag: '🇩🇲', countryCode: 'DM' },
    { name: 'Dominican Republic', nativeName: 'República Dominicana', code: '+1849', flag: '🇩🇴', countryCode: 'DO' },
    { name: 'Ecuador', nativeName: 'Ecuador', code: '+593', flag: '🇪🇨', countryCode: 'EC' },
    { name: 'Egypt', nativeName: 'مصر', code: '+20', flag: '🇪🇬', countryCode: 'EG' },
    { name: 'El Salvador', nativeName: 'El Salvador', code: '+503', flag: '🇸🇻', countryCode: 'SV' },
    { name: 'Equatorial Guinea', nativeName: 'Guinea Ecuatorial', code: '+240', flag: '🇬🇶', countryCode: 'GQ' },
    { name: 'Eritrea', nativeName: 'ኤርትራ', code: '+291', flag: '🇪🇷', countryCode: 'ER' },
    { name: 'Estonia', nativeName: 'Eesti', code: '+372', flag: '🇪🇪', countryCode: 'EE' },
    { name: 'Ethiopia', nativeName: 'ኢትዮጵያ', code: '+251', flag: '🇪🇹', countryCode: 'ET' },
    { name: 'Fiji', nativeName: 'Fiji', code: '+679', flag: '🇫🇯', countryCode: 'FJ' },
    { name: 'Finland', nativeName: 'Suomi', code: '+358', flag: '🇫🇮', countryCode: 'FI' },
    { name: 'France', nativeName: 'France', code: '+33', flag: '🇫🇷', countryCode: 'FR' },
    { name: 'Gabon', nativeName: 'Gabon', code: '+241', flag: '🇬🇦', countryCode: 'GA' },
    { name: 'Gambia', nativeName: 'Gambia', code: '+220', flag: '🇬🇲', countryCode: 'GM' },
    { name: 'Georgia', nativeName: 'საქართველო', code: '+995', flag: '🇬🇪', countryCode: 'GE' },
    { name: 'Germany', nativeName: 'Deutschland', code: '+49', flag: '🇩🇪', countryCode: 'DE' },
    { name: 'Ghana', nativeName: 'Ghana', code: '+233', flag: '🇬🇭', countryCode: 'GH' },
    { name: 'Greece', nativeName: 'Ελλάδα', code: '+30', flag: '🇬🇷', countryCode: 'GR' },
    { name: 'Grenada', nativeName: 'Grenada', code: '+1473', flag: '🇬🇩', countryCode: 'GD' },
    { name: 'Guatemala', nativeName: 'Guatemala', code: '+502', flag: '🇬🇹', countryCode: 'GT' },
    { name: 'Guinea', nativeName: 'Guinée', code: '+224', flag: '🇬🇳', countryCode: 'GN' },
    { name: 'Guinea-Bissau', nativeName: 'Guiné-Bissau', code: '+245', flag: '🇬🇼', countryCode: 'GW' },
    { name: 'Guyana', nativeName: 'Guyana', code: '+592', flag: '🇬🇾', countryCode: 'GY' },
    { name: 'Haiti', nativeName: 'Haïti', code: '+509', flag: '🇭🇹', countryCode: 'HT' },
    { name: 'Honduras', nativeName: 'Honduras', code: '+504', flag: '🇭🇳', countryCode: 'HN' },
    { name: 'Hungary', nativeName: 'Magyarország', code: '+36', flag: '🇭🇺', countryCode: 'HU' },
    { name: 'Iceland', nativeName: 'Ísland', code: '+354', flag: '🇮🇸', countryCode: 'IS' },
    { name: 'India', nativeName: 'भारत', code: '+91', flag: '🇮🇳', countryCode: 'IN' },
    { name: 'Indonesia', nativeName: 'Indonesia', code: '+62', flag: '🇮🇩', countryCode: 'ID' },
    { name: 'Iran', nativeName: 'ایران', code: '+98', flag: '🇮🇷', countryCode: 'IR' },
    { name: 'Iraq', nativeName: 'العراق', code: '+964', flag: '🇮🇶', countryCode: 'IQ' },
    { name: 'Ireland', nativeName: 'Éire', code: '+353', flag: '🇮🇪', countryCode: 'IE' },
    { name: 'Israel', nativeName: 'יִשְׂרָאֵל', code: '+972', flag: '🇮🇱', countryCode: 'IL' },
    { name: 'Italy', nativeName: 'Italia', code: '+39', flag: '🇮🇹', countryCode: 'IT' },
    { name: 'Jamaica', nativeName: 'Jamaica', code: '+1876', flag: '🇯🇲', countryCode: 'JM' },
    { name: 'Japan', nativeName: '日本', code: '+81', flag: '🇯🇵', countryCode: 'JP' },
    { name: 'Jordan', nativeName: 'الأردن', code: '+962', flag: '🇯🇴', countryCode: 'JO' },
    { name: 'Kazakhstan', nativeName: 'Қазақстан', code: '+7', flag: '🇰🇿', countryCode: 'KZ' },
    { name: 'Kenya', nativeName: 'Kenya', code: '+254', flag: '🇰🇪', countryCode: 'KE' },
    { name: 'Kiribati', nativeName: 'Kiribati', code: '+686', flag: '🇰🇮', countryCode: 'KI' },
    { name: 'Kuwait', nativeName: 'الكويت', code: '+965', flag: '🇰🇼', countryCode: 'KW' },
    { name: 'Kyrgyzstan', nativeName: 'Кыргызстан', code: '+996', flag: '🇰🇬', countryCode: 'KG' },
  { name: 'Laos', nativeName: 'ລາວ', code: '+856', flag: '🇱🇦', countryCode: 'LA' },
  { name: 'Latvia', nativeName: 'Latvija', code: '+371', flag: '🇱🇻', countryCode: 'LV' },
  { name: 'Lebanon', nativeName: 'لبنان', code: '+961', flag: '🇱🇧', countryCode: 'LB' },
  { name: 'Lesotho', nativeName: 'Lesotho', code: '+266', flag: '🇱🇸', countryCode: 'LS' },
  { name: 'Liberia', nativeName: 'Liberia', code: '+231', flag: '🇱🇷', countryCode: 'LR' },
  { name: 'Libya', nativeName: 'ليبيا', code: '+218', flag: '🇱🇾', countryCode: 'LY' },
  { name: 'Liechtenstein', nativeName: 'Liechtenstein', code: '+423', flag: '🇱🇮', countryCode: 'LI' },
  { name: 'Lithuania', nativeName: 'Lietuva', code: '+370', flag: '🇱🇹', countryCode: 'LT' },
  { name: 'Luxembourg', nativeName: 'Luxembourg', code: '+352', flag: '🇱🇺', countryCode: 'LU' },
  { name: 'Madagascar', nativeName: 'Madagasikara', code: '+261', flag: '🇲🇬', countryCode: 'MG' },
  { name: 'Malawi', nativeName: 'Malawi', code: '+265', flag: '🇲🇼', countryCode: 'MW' },
  { name: 'Malaysia', nativeName: 'Malaysia', code: '+60', flag: '🇲🇾', countryCode: 'MY' },
  { name: 'Maldives', nativeName: 'Dhivehi Raajje', code: '+960', flag: '🇲🇻', countryCode: 'MV' },
  { name: 'Mali', nativeName: 'Mali', code: '+223', flag: '🇲🇱', countryCode: 'ML' },
  { name: 'Malta', nativeName: 'Malta', code: '+356', flag: '🇲🇹', countryCode: 'MT' },
  { name: 'Marshall Islands', nativeName: 'M̧ajeļ', code: '+692', flag: '🇲🇭', countryCode: 'MH' },
  { name: 'Mauritania', nativeName: 'موريتانيا', code: '+222', flag: '🇲🇷', countryCode: 'MR' },
  { name: 'Mauritius', nativeName: 'Maurice', code: '+230', flag: '🇲🇺', countryCode: 'MU' },
  { name: 'Mexico', nativeName: 'México', code: '+52', flag: '🇲🇽', countryCode: 'MX' },
  { name: 'Micronesia', nativeName: 'Micronesia', code: '+691', flag: '🇫🇲', countryCode: 'FM' },
  { name: 'Moldova', nativeName: 'Moldova', code: '+373', flag: '🇲🇩', countryCode: 'MD' },
  { name: 'Monaco', nativeName: 'Monaco', code: '+377', flag: '🇲🇨', countryCode: 'MC' },
  { name: 'Mongolia', nativeName: 'Монгол улс', code: '+976', flag: '🇲🇳', countryCode: 'MN' },
  { name: 'Montenegro', nativeName: 'Crna Gora', code: '+382', flag: '🇲🇪', countryCode: 'ME' },
  { name: 'Morocco', nativeName: 'المغرب', code: '+212', flag: '🇲🇦', countryCode: 'MA' },
  { name: 'Mozambique', nativeName: 'Moçambique', code: '+258', flag: '🇲🇿', countryCode: 'MZ' },
  { name: 'Myanmar', nativeName: 'မြန်မာ', code: '+95', flag: '🇲🇲', countryCode: 'MM' },
  { name: 'Namibia', nativeName: 'Namibia', code: '+264', flag: '🇳🇦', countryCode: 'NA' },
  { name: 'Nauru', nativeName: 'Nauru', code: '+674', flag: '🇳🇷', countryCode: 'NR' },
  { name: 'Nepal', nativeName: 'नेपाल', code: '+977', flag: '🇳🇵', countryCode: 'NP' },
  { name: 'Netherlands', nativeName: 'Nederland', code: '+31', flag: '🇳🇱', countryCode: 'NL' },
  { name: 'New Zealand', nativeName: 'New Zealand', code: '+64', flag: '🇳🇿', countryCode: 'NZ' },
  { name: 'Nicaragua', nativeName: 'Nicaragua', code: '+505', flag: '🇳🇮', countryCode: 'NI' },
  { name: 'Niger', nativeName: 'Niger', code: '+227', flag: '🇳🇪', countryCode: 'NE' },
  { name: 'Nigeria', nativeName: 'Nigeria', code: '+234', flag: '🇳🇬', countryCode: 'NG' },
  { name: 'North Korea', nativeName: '조선민주주의인민공화국', code: '+850', flag: '🇰🇵', countryCode: 'KP' },
  { name: 'North Macedonia', nativeName: 'Северна Македонија', code: '+389', flag: '🇲🇰', countryCode: 'MK' },
  { name: 'Norway', nativeName: 'Norge', code: '+47', flag: '🇳🇴', countryCode: 'NO' },
  { name: 'Oman', nativeName: 'عمان', code: '+968', flag: '🇴🇲', countryCode: 'OM' },
  { name: 'Pakistan', nativeName: 'پاکستان', code: '+92', flag: '🇵🇰', countryCode: 'PK' },
  { name: 'Palau', nativeName: 'Palau', code: '+680', flag: '🇵🇼', countryCode: 'PW' },
  { name: 'Palestine', nativeName: 'فلسطين', code: '+970', flag: '🇵🇸', countryCode: 'PS' },
  { name: 'Panama', nativeName: 'Panamá', code: '+507', flag: '🇵🇦', countryCode: 'PA' },
  { name: 'Papua New Guinea', nativeName: 'Papua Niugini', code: '+675', flag: '🇵🇬', countryCode: 'PG' },
  { name: 'Paraguay', nativeName: 'Paraguay', code: '+595', flag: '🇵🇾', countryCode: 'PY' },
  { name: 'Peru', nativeName: 'Perú', code: '+51', flag: '🇵🇪', countryCode: 'PE' },
  { name: 'Philippines', nativeName: 'Pilipinas', code: '+63', flag: '🇵🇭', countryCode: 'PH' },
  { name: 'Poland', nativeName: 'Polska', code: '+48', flag: '🇵🇱', countryCode: 'PL' },
  { name: 'Portugal', nativeName: 'Portugal', code: '+351', flag: '🇵🇹', countryCode: 'PT' },
  { name: 'Qatar', nativeName: 'قطر', code: '+974', flag: '🇶🇦', countryCode: 'QA' },
  { name: 'Romania', nativeName: 'România', code: '+40', flag: '🇷🇴', countryCode: 'RO' },
  { name: 'Russia', nativeName: 'Россия', code: '+7', flag: '🇷🇺', countryCode: 'RU' },
  { name: 'Rwanda', nativeName: 'Rwanda', code: '+250', flag: '🇷🇼', countryCode: 'RW' },
  { name: 'Saint Kitts and Nevis', nativeName: 'Saint Kitts and Nevis', code: '+1869', flag: '🇰🇳', countryCode: 'KN' },
  { name: 'Saint Lucia', nativeName: 'Saint Lucia', code: '+1758', flag: '🇱🇨', countryCode: 'LC' },
  { name: 'Saint Vincent and the Grenadines', nativeName: 'Saint Vincent and the Grenadines', code: '+1784', flag: '🇻🇨', countryCode: 'VC' },
  { name: 'Samoa', nativeName: 'Samoa', code: '+685', flag: '🇼🇸', countryCode: 'WS' },
  { name: 'San Marino', nativeName: 'San Marino', code: '+378', flag: '🇸🇲', countryCode: 'SM' },
  { name: 'Sao Tome and Principe', nativeName: 'São Tomé e Príncipe', code: '+239', flag: '🇸🇹', countryCode: 'ST' },
  { name: 'Saudi Arabia', nativeName: 'المملكة العربية السعودية', code: '+966', flag: '🇸🇦', countryCode: 'SA' },
  { name: 'Senegal', nativeName: 'Sénégal', code: '+221', flag: '🇸🇳', countryCode: 'SN' },
  { name: 'Serbia', nativeName: 'Србија', code: '+381', flag: '🇷🇸', countryCode: 'RS' },
  { name: 'Seychelles', nativeName: 'Seychelles', code: '+248', flag: '🇸🇨', countryCode: 'SC' },
  { name: 'Sierra Leone', nativeName: 'Sierra Leone', code: '+232', flag: '🇸🇱', countryCode: 'SL' },
  { name: 'Singapore', nativeName: 'Singapore', code: '+65', flag: '🇸🇬', countryCode: 'SG' },
  { name: 'Slovakia', nativeName: 'Slovensko', code: '+421', flag: '🇸🇰', countryCode: 'SK' },
  { name: 'Slovenia', nativeName: 'Slovenija', code: '+386', flag: '🇸🇮', countryCode: 'SI' },
  { name: 'Solomon Islands', nativeName: 'Solomon Islands', code: '+677', flag: '🇸🇧', countryCode: 'SB' },
  { name: 'Somalia', nativeName: 'Soomaaliya', code: '+252', flag: '🇸🇴', countryCode: 'SO' },
  { name: 'South Africa', nativeName: 'South Africa', code: '+27', flag: '🇿🇦', countryCode: 'ZA' },
  { name: 'South Korea', nativeName: '대한민국', code: '+82', flag: '🇰🇷', countryCode: 'KR' },
  { name: 'South Sudan', nativeName: 'South Sudan', code: '+211', flag: '🇸🇸', countryCode: 'SS' },
  { name: 'Spain', nativeName: 'España', code: '+34', flag: '🇪🇸', countryCode: 'ES' },
  { name: 'Sri Lanka', nativeName: 'śrī laṃkāva', code: '+94', flag: '🇱🇰', countryCode: 'LK' },
  { name: 'Sudan', nativeName: 'السودان', code: '+249', flag: '🇸🇩', countryCode: 'SD' },
  { name: 'Suriname', nativeName: 'Suriname', code: '+597', flag: '🇸🇷', countryCode: 'SR' },
  { name: 'Sweden', nativeName: 'Sverige', code: '+46', flag: '🇸🇪', countryCode: 'SE' },
  { name: 'Switzerland', nativeName: 'Schweiz', code: '+41', flag: '🇨🇭', countryCode: 'CH' },
  { name: 'Syria', nativeName: 'سوريا', code: '+963', flag: '🇸🇾', countryCode: 'SY' },
  { name: 'Tajikistan', nativeName: 'Тоҷикистон', code: '+992', flag: '🇹🇯', countryCode: 'TJ' },
  { name: 'Tanzania', nativeName: 'Tanzania', code: '+255', flag: '🇹🇿', countryCode: 'TZ' },
  { name: 'Thailand', nativeName: 'ประเทศไทย', code: '+66', flag: '🇹🇭', countryCode: 'TH' },
  { name: 'Timor-Leste', nativeName: 'Timor-Leste', code: '+670', flag: '🇹🇱', countryCode: 'TL' },
  { name: 'Togo', nativeName: 'Togo', code: '+228', flag: '🇹🇬', countryCode: 'TG' },
  { name: 'Tonga', nativeName: 'Tonga', code: '+676', flag: '🇹🇴', countryCode: 'TO' },
  { name: 'Trinidad and Tobago', nativeName: 'Trinidad and Tobago', code: '+1868', flag: '🇹🇹', countryCode: 'TT' },
  { name: 'Tunisia', nativeName: 'تونس', code: '+216', flag: '🇹🇳', countryCode: 'TN' },
  { name: 'Turkey', nativeName: 'Türkiye', code: '+90', flag: '🇹🇷', countryCode: 'TR' },
  { name: 'Turkmenistan', nativeName: 'Türkmenistan', code: '+993', flag: '🇹🇲', countryCode: 'TM' },
  { name: 'Tuvalu', nativeName: 'Tuvalu', code: '+688', flag: '🇹🇻', countryCode: 'TV' },
  { name: 'Uganda', nativeName: 'Uganda', code: '+256', flag: '🇺🇬', countryCode: 'UG' },
  { name: 'Ukraine', nativeName: 'Україна', code: '+380', flag: '🇺🇦', countryCode: 'UA' },
  { name: 'United Arab Emirates', nativeName: 'الإمارات العربية المتحدة', code: '+971', flag: '🇦🇪', countryCode: 'AE' },
  { name: 'United Kingdom', nativeName: 'United Kingdom', code: '+44', flag: '🇬🇧', countryCode: 'GB' },
  { name: 'United States', nativeName: 'United States', code: '+1', flag: '🇺🇸', countryCode: 'US' },
  { name: 'Uruguay', nativeName: 'Uruguay', code: '+598', flag: '🇺🇾', countryCode: 'UY' },
  { name: 'Uzbekistan', nativeName: 'Uzbekiston', code: '+998', flag: '🇺🇿', countryCode: 'UZ' },
  { name: 'Vanuatu', nativeName: 'Vanuatu', code: '+678', flag: '🇻🇺', countryCode: 'VU' },
  { name: 'Vatican City', nativeName: 'Città del Vaticano', code: '+39', flag: '🇻🇦', countryCode: 'VA' },
  { name: 'Venezuela', nativeName: 'Venezuela', code: '+58', flag: '🇻🇪', countryCode: 'VE' },
  { name: 'Vietnam', nativeName: 'Việt Nam', code: '+84', flag: '🇻🇳', countryCode: 'VN' },
  { name: 'Yemen', nativeName: 'اليَمَن', code: '+967', flag: '🇾🇪', countryCode: 'YE' },
  { name: 'Zambia', nativeName: 'Zambia', code: '+260', flag: '🇿🇲', countryCode: 'ZM' },
  { name: 'Zimbabwe', nativeName: 'Zimbabwe', code: '+263', flag: '🇿🇼', countryCode: 'ZW' }
];