import React from "react";
import { DEMO_POSTS } from "@/data/posts";
import { PostDataType } from "@/data/types";
import Avatar from "@/shared/Avatar";
import Badge from "@/shared/Badge";
import ButtonPrimary from "@/shared/ButtonPrimary";
import ButtonSecondary from "@/shared/ButtonSecondary";
import Comment from "@/shared/Comment";
import SocialsList from "@/shared/SocialsList";
import Textarea from "@/shared/Textarea";
import Image from "next/image";
import travelhero2Image from "@/images/company/privacypolicy.png";
import Link from "next/link";
import { Route } from "@/routers/types";

const Page = ({
    params,
    searchParams,
}: {
    params: { stepIndex: string };
    searchParams?: { [key: string]: string | string[] | undefined };
}) => {
    const renderHeader = () => {
        return (
            <header className="container rounded-xl">
                <div className="max-w-screen-md mx-auto space-y-5">
                    <h1
                        className=" text-neutral-900 font-semibold text-5xl md:text-5xl md:!leading-[120%] lg:text-5xl dark:text-neutral-100 max-w-4xl flex justify-center"
                        title="Quiet ingenuity: 120,000 lunches and counting"
                    >
                        Privacy Policy
                    </h1>
                    <div className="w-full border-b border-neutral-100 dark:border-neutral-800"></div>
                </div>
            </header>
        );
    };

    const renderContent = () => {
        return (
            <div
                id="single-entry-content"
                className="prose dark:prose-invert prose-sm !max-w-screen-md sm:prose lg:prose-lg mx-auto dark:prose-dark"
            >
                <p>
                    {`This page outlines TickYourList's (registered under Scrollit) privacy policy, elucidating the collection, usage, and/or disclosure of personal information by TickYourList. Please review it thoroughly.`}
                </p>
                <p>
                    This <strong>Privacy Policy</strong> {`is applicable to our website, and its related subdomains (collectively referred to as our "Service"), along with our application, TickYourList. By accessing or utilizing our Service, or by directly contacting or engaging with us, you indicate that you have read, comprehended, and consent to our collection, storage, usage, and disclosure of your personal information as delineated in this Privacy Policy and our Terms of Service.`}
                </p>
                <ol>
                    <li>Definitions and Key Terms</li>
                    <ul>
                        <h2>For the purposes of this Privacy Policy:</h2>
                        <li>
                            <strong>Affiliated Companies:</strong> Any person or entity that directly or indirectly controls, is controlled by, or is under common control with TickYourList, whether through ownership or otherwise.
                        </li>
                        <li>
                            <strong>Cookie(s):</strong> Small pieces of data generated by a website and stored by your browser.
                        </li>
                        <li><strong>Company:</strong> The entity responsible for your information under this privacy policy, TickYourList, registered under Scrollit.</li>
                        <li><strong>Device:</strong> Includes phones, tablets, computers, or any other internet-connected device.</li>
                        <li><strong>IP Address:</strong> A unique number assigned to each device connected to the Internet.</li>
                        <li><strong>Personal Data:</strong> Any information that directly, indirectly, or in conjunction with other information enables the identification of a natural person.</li>
                    </ul>
                    <li>
                        Application of Privacy Policy
                        <p>This Privacy Policy applies to our Services – the Website, its associated subdomains, and our application. By using TickYourList or contacting us directly, you signify your acceptance of this Privacy Policy.</p>
                    </li>
                    <li>
                        Information Collected and Processed by TickYourList
                        <p>We collect and process information from and about you to provide the Services in a more personalized and relevant manner. Information collected and processed may include contact information, billing and payment details, and device information.</p>
                    </li>
                    <li>
                        Purpose and Use of Collected Information
                        <p>Your Personal Information collected while accessing TickYourList is utilized solely for lawful purposes and with the aim of providing you with our services. This encompasses delivering pertinent content and tailored experiences.</p>
                    </li>
                    <li>
                        Information Sharing
                        <p>We may utilize and need to share information with certain Service Providers and/or other Third Parties. This may include advertisers, content sponsors, promotional and marketing partners, and others.</p>
                    </li>
                    <li>
                        Information Storage, Transfer, Deletion, and Retention
                        <p>Your Personal Information is retained on our servers for as long as necessary to fulfill the purpose for which it was collected. TickYourList is based in India but offers Services to users in various jurisdictions.</p>
                    </li>
                    <li>
                        Information Security
                        <p>We implement a variety of security measures to maintain the safety of your personal information. We offer the use of a secure server and enforce various physical, electronic, and managerial procedures to help safeguard your information.</p>
                    </li>
                    <li>
                        Update Information
                        <p>You have the right to request updates or corrections to the information TickYourList collects. This includes changing your preferences regarding communications and other information you receive from us.</p>
                    </li>
                    <li>
                        Governing Law and Choice of Forum
                        <p>This Privacy Policy is governed by the laws of India. You consent to the exclusive jurisdiction of the courts in connection with any action or dispute arising under or in connection with this Privacy Policy.</p>
                    </li>
                    <li>
                        External Links
                        <p>This Privacy Policy solely applies to the Services as defined. The Services and/or the Service Providers may contain links to other external websites not operated or controlled by TickYourList.</p>
                    </li>
                    <li>
                        {`Children's Data`}
                        <p>Our Services are not intended for nor directed towards children. We will only knowingly collect or process information pertaining to children if it is provided by and with the consent of a parent or guardian.</p>
                    </li>
                    <li>
                        Privacy Policy Changes
                        <p>We may update this Privacy Policy in the future. Changes to this Privacy Policy are applicable and effective when they are posted on this page.</p>
                    </li>
                    <li>
                        Contact
                        <p>If you have any inquiries regarding the details of this Privacy Policy, please contact us at <a href="help@tickyourlist.com">help@tickyourlist.com</a></p>
                    </li>
                </ol>
                <blockquote><p><strong>This Privacy Policy is effective as of 21/03/2024 and was last updated on 21/03/2024.</strong></p></blockquote>
                {/* <figure>
                    <Image src={travelhero2Image} alt="blog" className="rounded-2xl" />
                    <figcaption>
                        <p>This page outlines TickYourList's (registered under Scrollit) privacy policy, elucidating the collection, usage, and/or disclosure of personal information by TickYourList. Please review it thoroughly.</p>
                        <p>This Privacy Policy is applicable to our website, and its related subdomains (collectively referred to as our "Service"), along with our application, TickYourList. By accessing or utilizing our Service, or by directly contacting or engaging with us, you indicate that you have read, comprehended, and consent to our collection, storage, usage, and disclosure of your personal information as delineated in this Privacy Policy and our Terms of Service.</p>

                    </figcaption>
                </figure> */}
            </div>
        );
    };

    const renderTags = () => {
        return (
            <div className="max-w-screen-md mx-auto flex flex-wrap">
                <a
                    className="nc-Tag inline-block bg-white text-sm text-neutral-600 dark:text-neutral-300 py-2 rounded-lg border border-neutral-100  md:px-4 dark:bg-neutral-700 dark:border-neutral-700 hover:border-neutral-200 dark:hover:border-neutral-6000 mr-2 mb-2"
                    href="##"
                >
                    Garden
                </a>
                <a
                    className="nc-Tag inline-block bg-white text-sm text-neutral-600 dark:text-neutral-300 py-2 rounded-lg border border-neutral-100  md:px-4 dark:bg-neutral-700 dark:border-neutral-700 hover:border-neutral-200 dark:hover:border-neutral-6000 mr-2 mb-2"
                    href="##"
                >
                    Jewelry
                </a>
                <a
                    className="nc-Tag inline-block bg-white text-sm text-neutral-600 dark:text-neutral-300 py-2 rounded-lg border border-neutral-100  md:px-4 dark:bg-neutral-700 dark:border-neutral-700 hover:border-neutral-200 dark:hover:border-neutral-6000 mr-2 mb-2"
                    href="##"
                >
                    Tools
                </a>
            </div>
        );
    };

    const renderAuthor = () => {
        return (
            <div className="max-w-screen-md mx-auto ">
                <div className="nc-SingleAuthor flex">
                    <Avatar sizeClass="w-11 h-11 md:w-24 md:h-24" />
                    <div className="flex flex-col ml-3 max-w-lg sm:ml-5 space-y-1">
                        <span className="text-xs text-neutral-400 uppercase tracking-wider">
                            WRITEN BY
                        </span>
                        <h2 className="text-lg font-semibold text-neutral-900 dark:text-neutral-200">
                            <a href="/">Fones Mimi</a>
                        </h2>
                        <span className="text-sm text-neutral-500 sm:text-base dark:text-neutral-300">
                            There’s no stopping the tech giant. Apple now opens its 100th
                            store in China.There’s no stopping the tech giant.
                            <a className="text-primary-6000 font-medium ml-1" href="/">
                                Readmore
                            </a>
                        </span>
                    </div>
                </div>
            </div>
        );
    };

    const renderCommentForm = () => {
        return (
            <div className="max-w-screen-md mx-auto pt-5">
                <h3 className="text-xl font-semibold text-neutral-800 dark:text-neutral-200">
                    Responses (14)
                </h3>
                <form className="nc-SingleCommentForm mt-5">
                    <Textarea />
                    <div className="mt-2 space-x-3">
                        <ButtonPrimary>Submit</ButtonPrimary>
                        <ButtonSecondary>Cancel</ButtonSecondary>
                    </div>
                </form>
            </div>
        );
    };

    const renderCommentLists = () => {
        return (
            <div className="max-w-screen-md mx-auto">
                <ul className="nc-SingleCommentLists space-y-5">
                    <li>
                        <Comment />
                        <ul className="pl-4 mt-5 space-y-5 md:pl-11">
                            <li>
                                <Comment isSmall />
                            </li>
                        </ul>
                    </li>
                    <li>
                        <Comment />
                        <ul className="pl-4 mt-5 space-y-5 md:pl-11">
                            <li>
                                <Comment isSmall />
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        );
    };

    const renderPostRelated = (post: PostDataType) => {
        return (
            <div
                key={post.id}
                className="relative aspect-w-3 aspect-h-4 rounded-3xl overflow-hidden group"
            >
                <Link href={post.href as Route} />
                <Image
                    className="object-cover transform group-hover:scale-105 transition-transform duration-300"
                    src={post.featuredImage}
                    fill
                    sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
                    alt=""
                />
                <div>
                    <div className="absolute bottom-0 inset-x-0 h-1/2 bg-gradient-to-t from-black"></div>
                </div>
                <div className="flex flex-col justify-end items-start text-xs text-neutral-300 space-y-2.5 p-4">
                    <Badge name="Categories" />
                    <h2 className="block text-lg font-semibold text-white ">
                        <span className="line-clamp-2">{post.title}</span>
                    </h2>

                    <div className="flex">
                        <span className="block text-neutral-200 hover:text-white font-medium truncate">
                            {post.author.displayName}
                        </span>
                        <span className="mx-1.5 font-medium">·</span>
                        <span className="font-normal truncate">{post.date}</span>
                    </div>
                </div>
                <Link href={post.href as Route} />
            </div>
        );
    };

    return (
        <div className="nc-PageSingle pt-8 lg:pt-16 ">
            {renderHeader()}
            <div className="container my-10 sm:my-12 ">
                <Image className="w-full rounded-xl" src={travelhero2Image} alt="" />
            </div>

            <div className="nc-SingleContent container space-y-10">
                {renderContent()}
                {/* {renderTags()}
                <div className="max-w-screen-md mx-auto border-b border-t border-neutral-100 dark:border-neutral-700"></div>
                {renderAuthor()}
                {renderCommentForm()} */}
                {/* {renderCommentLists()} */}
            </div>
            <div className="relative bg-neutral-100 dark:bg-neutral-800 py-16 lg:py-28 mt-16 lg:mt-24">
                <div className="container ">
                    <h2 className="text-3xl font-semibold">New blogs</h2>
                    <div className="mt-10 grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6 md:gap-8">
                        {/*  */}
                        {DEMO_POSTS.filter((_, i) => i < 4).map(renderPostRelated)}
                        {/*  */}
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Page;
